[package]
name = "chemquiz"
version = "0.1.0"
edition = "2024"

[dependencies]
console_error_panic_hook = "0.1"
getrandom = { version = "0.2", features = ["js"] }
leptos = { version = "0.6", features = ["csr"] }
rand = "0.8"
thiserror = "1.0"
wasm-bindgen = "0.2"
